services:
  test-node-backend-postgres:
    build:
      context: .
      target: production
    image: test-node-backend-postgres
    container_name: test-node-backend-postgres
    depends_on:
      - test-node-backend-postgres-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: test-node-backend-postgres-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
  test-node-backend-postgres-postgres:
    image: postgres:15.6-alpine
    environment:
      POSTGRES_DB: test-node-backend-postgres
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres